### ISSUE TITLE
Question text does not show if it contains special html characters

### ISSUE THREAD

**Issue by fjwong** [sujrd/faiadashu#48]
For example, with the following Questionnaire:

```
{
  "resourceType": "Questionnaire",
  "name": "test",
  "title": "Test Form",
  "status": "active",
  "item": [
    {
      "linkId": "age",
      "text": "Patient age is < 60?",
      "type": "boolean"
    }
  ]
}
```

The `text` does not get rendered due to the `<` within the text itself, and a `simple_html_css` parsing error is logged to console.

**Comment by ajsviado** [comment]
Update: After investigation I found that the problem is caused by a 3rd party library https://pub.dev/packages/simple_html_css used for rendering html strings

The problem only happens when there is a < symbol on the string. I have tested with > and the question is still rendered.
Here is the sample question that I used for testing:
- Is the patient on < > anticoagulant / blood thinners?

During processing of the question details faiadashu escapes all html symbols and transforms the text to the one seen below
- Is the patient on &lt; &gt; anticoagulant &#47; blood thinners?.

The string is then passed to the method HTML.toSpanText() to be displayed. This method is part of the 3rd party library which will throw an error:

```
simple_html_css Exception: XmlParserException: "<!DOCTYPE" expected at 1:22
2023-10-19 16:16:33.689 20062-20099 flutter                 com.legentix.faiagallery             I  simple_html_css Stack Trace: #0      XmlEventIterator.moveNext (package:xml/src/xml_events/iterator.dart:35:9)
2023-10-19 16:16:33.689 20062-20099 flutter                 com.legentix.faiagallery             I  #1      Parser.parse (package:simple_html_css/src/internals.dart:150:34)
2023-10-19 16:16:33.689 20062-20099 flutter                 com.legentix.faiagallery             I  #2      HTML.toTextSpan (package:simple_html_css/src/html_stylist.dart:83:21)
2023-10-19 16:16:33.689 20062-20099 flutter                 com.legentix.faiagallery             I  #3      QuestionnaireItemFillerTitle.build (package:faiadashu/questionnaires/view/item/src/questionnaire_item_filler_title.dart:91:24)
2023-10-19 16:16:33.689 20062-20099 flutter                 com.legentix.faiagallery             I  #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:5156:49)
2023-10-19 16:16:33.689 20062-20099 flutter                 com.legentix.faiagallery             I  #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
2023-10-19 16:16:33.689 20062-20099 flutter                 com.legentix.faiagallery             I  #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
```

The current version of the library that we are using is 3.0.1 which I upgraded to 4.0.0 but the problem still exists.
- simple_html_css 4.0.0 (was 3.0.1+1)

I found that the faiadashu developer tiloc also reported this issue on the library
https://github.com/ali-thowfeek/simple_html_css_flutter/issues/17

**Comment by fjwong** [comment]
@ajsviado Thank you for the investigation. I thought the issue would be simpler to handle, but apparently it's not. Sorry for the troubles.

I'll try to look into this myself as well.

**Comment by ajsviado** [comment]
I found a library called https://pub.dev/packages/css_text which is the parent repository of https://pub.dev/packages/simple_html_css. I was able to migrate the calls on HTML.toTextSpan to the new library but cannot test it yet because the problem on petitparser is happening again: https://git.allm.net/fhir-forms/smart-forms-flutter-sdk/-/issues/55. I already tried to force petitparser to version 5.1.0 but still can't build the project. Will try again tomorrow

**Comment by fjwong** [comment]
@ajsviado Thanks for looking into this.

From what I can see, Faiadashu would end up converting the question text `Patient age is < 60?` into valid html with escaped characters `<p>Patient age is &lt; 60?</p>`.

The problem appears to be that in the `simple_html_css` package, on [this line](https://github.com/ali-thowfeek/simple_html_css_flutter/blob/main/lib/src/html_stylist.dart#L76). The html content is being unescaped for some reason, which ends up resulting in a html string like `<p>Patient age is < 60?</p>` which should be no longer strictly valid html.

Thus far, I could come up with two ways to handle this (without changing libraries):
1. Submit a PR to `simple_html_css` with the html unescaping removed, and hope to get it merged then update the package (although I'm not sure if that would cause some other issues).
2. Replace `<` in the text for `&amp;lt;`, which would basically be converted to `<p>Patient age is &lt; 60?</p>` when passed to `simple_html_css`.

**Comment by fjwong** [comment]
@ajsviado I was looking at this earlier and pushed a workaround for this here: https://github.com/sujrd/faiadashu/pull/59

Of course, if you have a better way to address this in the meantime, or manage to get the other library to work without issues etc, please let me know.

**Comment by fjwong** [comment]
Closing, as #59 has already been merged. Further improvements are to be handled later on in #62.
